CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(25)                             NOT NULL,
    email       VARCHAR(100)                            NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    first_name  VARCHAR(50),
    last_name   VARCHAR(50),
    provider    VARCHAR(20),
    provider_id VARCHAR(100),
    enabled     BOOLEAN,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);